# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6126740082ca4c76d871a8287380f4846c3779c59db61b6a32cb8de708077f5f84f8bf8331afd95768fadb013f3a0f58dbc3f2ce97248790108e741aee0dfca

test:
  secret_key_base: 3a11c62b61856359000e19b021a976dd07cff515641b80216e17d661606ad863b56313f45bdef8d67cfd371ffa2c9a16d0f9e48d6e8b4711d5a57315e6e76ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
